const fetch = require('node-fetch');

(async () => {
  try {
    const res = await fetch('http://localhost:3000/api/item/update', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        id: "custom-1776529568485",
        title: "LivingPaper Studioparty [TEST BY AI]",
        description: "This is a test description generated by the representation AI direct update loop!"
      })
    });
    const data = await res.json();
    console.log(data);
  } catch (e) {
    console.error(e.message);
  }
})();
